### ISSUE TITLE
Add download method for PCMPlayer class

### ISSUE THREAD

**Issue by Axibord** [pkjy/pcm-player#10]
Would it be possible to add a .download() method on PCMPlayer? Since it's raw PCM data, I'd like to download a .wav or .pcm file that is ready to be read with VLC or another media player directly. I thought since you already added the corresponding Header for the web version to work, can you implement the .download() method or guide me a little so i can do it myself (I don't have knowledge on audio data i might do wrong things). Thanks

**Comment by pkjy** [comment]
> Would it be possible to add a .download() method on PCMPlayer? Since it's raw PCM data, I'd like to download a .wav or .pcm file that is ready to be read with VLC or another media player directly. I thought since you already added the corresponding Header for the web version to work, can you implement the .download() method or guide me a little so i can do it myself (I don't have knowledge on audio data i might do wrong things). Thanks

if you just want to download file, direct download the file may be the better way [download file from url](https://stackoverflow.com/questions/43810700/how-to-download-audio-file-from-url-in-node-js) and you don't need to play it :D
