### ISSUE TITLE
请问后端传过来的ArrayBufer是什么样子的，作者介意给截图一下吗

### ISSUE THREAD

**Issue by ericjiajia** [pkjy/pcm-player#11]
目前对接的是java后端，直接ws传过来的是bytes数组，我在前端用Uint8Array转化了一下，不知道是否可行？看作者方便提供一下联系方式，加下wx或者qq交流一下吗~感谢

**Comment by pkjy** [comment]
可以直接传bytes过来的，demo里面的服务端也是通过二进制传给前端的。前端可以直接通过websocket接收数据然后调用播放就好了。我demo里面给的就是通过websocket接收数据并播放。

websocket内的数据截图，你可以直接去我的在线[demo网页](https://pkjy.github.io/pcm-player/)里，按F12打开控制台查看。

![image](https://github.com/pkjy/pcm-player/assets/14119424/6620e927-c6c0-4849-84bd-384ed9d21c4c)

**Comment by ericjiajia** [comment]
非常感谢回复，但您的demo目前使用调用demo会有报错，所以才无从参考
![image](https://github.com/pkjy/pcm-player/assets/26456192/fa97accd-db82-4afe-8fc6-2bdfbbb721ec)

**Comment by pkjy** [comment]
我这能正常播放，这个报错看着像是没成功加载我的js文件（[https://unpkg.com/pcm-player](https://unpkg.com/pcm-player)），你试试看这个文件能正常访问吗？如果不行就打开科学上网试试。 
我主动拦截掉这个js文件能复现你的这个报错，多半是js资源加载失败导致的。
