### ISSUE TITLE
typescript类型定义问题

### ISSUE THREAD

**Issue by kuige** [pkjy/pcm-player#13]
<img width="638" alt="image" src="https://github.com/pkjy/pcm-player/assets/8212800/e7795ccd-be35-450d-a1a0-7fb013d7bf6f">

后面两个参数的类型定义写错了吧？eslint会报错，应该改为这样？
```
onstatechange: (node: AudioContext, event: Event, type: AudioContextState) => void
onended: (node: AudioBufferSourceNode, event: Event) => void
```
另外这两个参数可以改为可选吗？

**Comment by kuige** [comment]
@pkjy npm package可以更新一下吗？

**Comment by pkjy** [comment]
> @pkjy npm package可以更新一下吗？

更新了 https://www.npmjs.com/package/pcm-player?activeTab=readme
