### ISSUE TITLE
无法播放ffmpeg编码s16be格式的pcm音频，s16le可以小端序字节可以

### ISSUE THREAD

**Issue by co1a1982** [pkjy/pcm-player#15]
如题，后续会添加支持吗

**Comment by pkjy** [comment]
提供一下s16be和s16le的资源？

**Comment by co1a1982** [comment]
[pcm.zip](https://github.com/pkjy/pcm-player/files/14138049/pcm.zip)

感谢回复

我用ffmpeg将你示例文件16bit-8000.pcm转为了s16be：
`ffmpeg -acodec pcm_s16le -f s16le -ar 8000 -ac 2 -i ./16bit-8000.pcm -acodec pcm_s16be -ar 8000 -ac 2 -f s16be ./16bit-8000-2-s16be.pcm`
使用ffplay播放是可以的：
`ffplay -i ./16bit-8000-1-s16be.pcm -ar 8000 -ac 2 -f s16be`

还有音频播放不太顺畅，是我配置flushTime不对的原因吗？如果是该如何配置

**Comment by pkjy** [comment]
因为直接调用web的AudioContext播放，可能是浏览器不支持直接播放。暂时先用ffmpeg统一处理成s16le吧。稍微看了下s16le和s16be数据位置是不同排列的。
