### ISSUE TITLE
safari for ios没有声音.

### ISSUE THREAD

**Issue by i-query** [pkjy/pcm-player#3]
safari for ios没有声音,有没有人遇到过.

**Comment by pkjy** [comment]
> safari for ios没有声音,有没有人遇到过.

Safari浏览器播放的音频数据，采样率不能低于22050Hz。可能跟这块有关？尤其是IOS上很多奇奇妙妙的BUG，以前做相关内容的时候有碰到过，具体的可以在[websocket pcm webaudio 记录](https://github.com/pkjy/blog/issues/6)看下。
