### ISSUE TITLE
您好，请问能处理音频降噪吗

### ISSUE THREAD

**Issue by sunkingsss** [pkjy/pcm-player#4]

**Comment by pkjy** [comment]
这个DEMO只是对PCM数据流的播放，其他对PCM数据的处理需要自己写算法哦。还可以用一些软件例如 speex 等软件对数据进行降噪等处理。相关npm包有 [Speex Resampler](https://www.npmjs.com/package/speex-resampler) 之类的。

**Comment by sunkingsss** [comment]
那请问可以使用BiquadFilterNode低阶滤波器来处理降噪吗？主要处理电流声

**Comment by pkjy** [comment]
实例化以后，可以通过`audioCtx`访问到当前[AudioContext](https://developer.mozilla.org/zh-CN/docs/Web/API/AudioContext/AudioContext)。随后你想用AudioContext相关的什么API都能操作了。

eg:
``` javascript
const player = new PCMPlayer({
        inputCodec: 'Int16',
        channels: 2,
        sampleRate: 8000,
        flushTime: 200
});
console.log('AudioContext here', player.audioCtx)
```

**Comment by FickXu** [comment]
> 那请问可以使用BiquadFilterNode低阶滤波器来处理降噪吗？主要处理电流声

请问噪音的问题你解决了吗？

**Comment by pkjy** [comment]
> > 那请问可以使用BiquadFilterNode低阶滤波器来处理降噪吗？主要处理电流声
> 
> 请问噪音的问题你解决了吗？

音量初始值太高了，gainNode范围0~1之间，我把demo和代码里调低了些，可以再访问demo试试。
