### ISSUE TITLE
A new feature - a callback function that is fired when audio is played out

### ISSUE THREAD

**Issue by Evgenii-Gorbushin** [pkjy/pcm-player#7]
Hi,

May I propose a new feature to your project? The feature is to add a new property (onended) to the options. The property is optional and can be assinged to a callback function that is fired when audio is played out. I could make a pull request if you don't mind.

Best regards

**Comment by pkjy** [comment]
Thanks for your suggestion. I think the pcm data was played like stream ,the data is continuous send from the server or other side. In the current usage scenarios I encounter,when the pcm data comes from server we will need to play in the client side(like pc browser), and client side don't konw whether the audio is supposed to be end. So strictly speaking, it is difficult to judge whether this audio is really played out.

At the same time , I found AudioContext only has an event named [statechange](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/statechange_event) ,and it's fired when calling suspend or resume or close .

**Comment by Evgenii-Gorbushin** [comment]
Thank you for your response)

I'll explain my idea more clearly, just for your information. In the code, there is the flush() method where BufferSource is created, like this:
`var buffer Source = this.audioCtx.createBufferSource();`
And BufferSource has a method called "onended", which fires whenever audio is played out. So, I modified the code, as you may see in an attached screenshot, and it works very well. It fires in a proper moment when streaming audio, which is located on an outside server, is played out.

<img width="833" alt="Screenshot_2022 07 17_02" src="https://user-images.githubusercontent.com/43174102/179467709-1206704e-f17d-4772-af7d-364e940c1f8a.png">

Best regards

**Comment by pkjy** [comment]
> Thank you for your response)
> 
> I'll explain my idea more clearly, just for your information. In the code, there is the flush() method where BufferSource is created, like this: `var buffer Source = this.audioCtx.createBufferSource();` And BufferSource has a method called "onended", which fires whenever audio is played out. So, I modified the code, as you may see in an attached screenshot, and it works very well. It fires in a proper moment when streaming audio, which is located on an outside server, is played out.
> 
> <img alt="Screenshot_2022 07 17_02" width="833" src="https://user-images.githubusercontent.com/43174102/179467709-1206704e-f17d-4772-af7d-364e940c1f8a.png">
> 
> Best regards

yes, I also read this api, but every buffer is a small fragment, and this onended event will be fired many times. I don't know if this is useful or necessary. 😕

**Comment by Evgenii-Gorbushin** [comment]
I need the onended event in my case of usage of pcm-player, so I had to add it manually. I would ask you to add the onended event as an option, as you did with statechange. Just make it optional in d.ts.
Thanks.

**Comment by pkjy** [comment]
pls check v0.0.15

**Comment by Evgenii-Gorbushin** [comment]
Thank you a lot, onended works fine :)

Also, I've tested onstatechange and got an issue in console on second run of pcm-player.

<img width="422" alt="Screenshot_2022 07 19_01" src="https://user-images.githubusercontent.com/43174102/179809777-c24a42f8-474c-418c-8f04-027b44c1ef9e.png">
<img width="440" alt="Screenshot_2022 07 19_02" src="https://user-images.githubusercontent.com/43174102/179809845-43bad710-d4ab-4ee1-8c41-45f563462428.png">

If I change the code like in the screenshot below the issue is gone.

<img width="487" alt="Screenshot_2022 07 19_03" src="https://user-images.githubusercontent.com/43174102/179810156-888cefc9-93f8-4b4c-87a3-14e594303e04.png">

Best regards

**Comment by kuige** [comment]
@pkjy onended 回调函数可以添加一个参数，表示当前的pcm数据是否已播放完吗？不用管后面是否还会通过 feed 方法添加新的 pcm 数据，但是需要知道 onended 调用的那一刻，是否已有的数据都已经播完了

如果有这个参数，还能结合其他条件来判断是否全部播放结束，否则真不好处理 😂
