### ISSUE TITLE
Not working on ios safari

### ISSUE THREAD

**Issue by jmsucasas** [pkjy/pcm-player#9]
Hi,
If i try to play the example into a ios 15 iphone, it does not work. How can i fix it?

br

**Comment by pkjy** [comment]
> Hi, If i try to play the example into a ios 15 iphone, it does not work. How can i fix it?
> 
> br

there's many possibility, pls try my online demo [pcm-player demo](https://pkjy.github.io/pcm-player/) first and see if it works. demo still woking on my ios15.7.
